### ISSUE TITLE
How to provide "User Configuration"

### ISSUE THREAD

**Issue by frank-emrich** [freebroccolo/ocaml-language-server#117]
Hi, I would like to set a custom path to my ocaml executables, like ocamlfind and ocamlmerlin. I see the following error message produced in the code:
Double check your path or try configuring "reason.path.ocamlmerlin" under "User Settings"

How do I set those "User Settings"? I guess I have to put a .json file somewhere? I see that 
src/lib/index.ts defines an interface for those settings, but I cannot find where these settings are actually set/parsed from a file in the code base.

**Comment by frank-emrich** [comment]
Not from my side, sorry

**Comment by AZanellato** [comment]
Did you run `opam user-setup install`? I had this problem running this

**Comment by frank-emrich** [comment]
I'm not sure what I did back then, but I'm also not using that particular setup any more.

**Comment by PBhandari99** [comment]
Any solutions here?

**Comment by AZanellato** [comment]
The issue is closed, can you at least provide a bit more information @PBhandari99 ?

Did you try `opam user-setup install`?
