### ISSUE TITLE
textDocument/didChange event does not work if `range` is omitted

### ISSUE THREAD

**Issue by extr0py** [freebroccolo/ocaml-language-server#22]
One blocker for integration with Oni (https://github.com/extr0py/oni/pull/488) is that, in some cases, Oni sends the full document text via `textDocument/didChange` to the language server. This can happen if edits are made in normal mode, and currently, there isn't a convenient way to diff these - so Oni sends over the full content through a `textDocument/didChange` event. I'd like to fix this eventually, but it might be painful in the short-term. This fix would be useful for any lightweight LSP client that is "poorly behaved" in that it always does a full sync, even though this LSP server specifies incremental sync.

In the full-sync case, the `range` parameter is omitted, which should be supported according to the spec:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_didChange

It looks like the implementation of the language server, though, always assumes that `range` will be specified on the `didChange` event:
```
this.session.connection.onDidChangeTextDocument(async (event): Promise<void> => {
      for (const change of event.contentChanges) {
        if (change && change.range) {
          const oldDocument = this.textDocuments.get(event.textDocument.uri);
...
```

A fix for this would be to handle the case where range is omitted as basically the same as the `onDidOpenTextDocument`, using the text passed in from the content change.

Thanks for the great work on this language server! Let me know if you need any clarifications.

**Comment by freebroccolo** [comment]
I see. If I understand correctly, I think it shouldn't be too hard to address this. I'll take a look.

**Comment by extr0py** [comment]
Cool, I think it should be (relatively) straightforward too, looking at `synchronizer.ts`. I'm happy to help here with a PR as well if you're working on other things!

**Comment by freebroccolo** [comment]
Yeah, I've been a little bit short on time this week but I plan to do some work on the server this weekend. But if you are interested in submitting a PR that would certainly be welcome!

**Comment by extr0py** [comment]
Definitely, know how that goes! Sweet, I'll work on a PR and submit it shortly.
