### ISSUE TITLE
Possible to release new NPM version?

### ISSUE THREAD

**Issue by extr0py** [freebroccolo/ocaml-language-server#23]
It looks like the latest package for ocaml-language-server is out-of-date - it was last updated 4 months ago. There have been several fixes between then and now.

It'd make it easier to consume this language server from Oni (https://github.com/extr0py/oni/pull/488), either via a `package.json` dependency or directly installed by `npm install -g`.

Thanks!

**Comment by freebroccolo** [comment]
Yeah, I was just thinking about this earlier. I've been planning a release soon but was waiting on a few other items first. But I can just go ahead and make an interim release. I'll take a look at doing that tomorrow or so.

**Comment by extr0py** [comment]
Awesome, thanks @freebroccolo !

**Comment by freebroccolo** [comment]
Sorry for the delay on this. New version is released now.
