### ISSUE TITLE
Make dependencyEnv detection cross platform

### ISSUE THREAD

**Issue by fhelwanger** [freebroccolo/ocaml-language-server#27]
I was trying to make ocaml and reason work on windows through WSL. More info here: https://github.com/reasonml/reason-cli/issues/35#issuecomment-319727823

It worked fine until I tested the vscode-reasonml extension on one machine where it can't find `sh` because I don't have cygwin or something similar installed.

The problem is because of that:

https://github.com/freebroccolo/ocaml-language-server/blob/master/src/server/session/environment.ts#L62

Could the dependencyEnv detection be made in JavaScript, so it won't crash on windows?

**Comment by chenglou** [comment]
Btw dependency-env is deprecated. We can & should remove it completely

**Comment by fhelwanger** [comment]
OK, I created #29 to remove it.
