### ISSUE TITLE
Invalid line numbers being sent to diagnostics

### ISSUE THREAD

**Issue by jchavarri** [freebroccolo/ocaml-language-server#34]
When having a Reason file like:

```reason
/* test.re */
while (current <: !(length input)) {
};
```

It seems the query results from Merlin include a negative line number so the extension chokes with:

`Notification handler 'textDocument/publishDiagnostics' failed with message: Illegal argument: line must be positive`

@freebroccolo @let-def @chenglou I think this can be solved in here, but maybe the case is useful to be treated upstream in `ocaml/merlin`?

**Comment by chenglou** [comment]
And super-errors & your work on #32 solves it, right?

OCaml line logics is super weird, here's how I streamlined them: https://github.com/BuckleScript/bucklescript/blob/bc53ffd5a178d023407760a1fdcbda35345b1584/jscomp/super_errors/super_location.ml#L70 https://github.com/BuckleScript/bucklescript/blob/bc53ffd5a178d023407760a1fdcbda35345b1584/jscomp/super_errors/super_misc.ml#L36

**Comment by jchavarri** [comment]
> And super-errors & your work on #32 solves it, right?

No, I checked that even bsb w/ super-errors fails to output line numbers or file data as well. I didn't debug it but this is the output from the command line:

```
BSB check build spec : OK 
ninja.exe -C lib/bs 
ninja: Entering directory `lib/bs'
[1/1] Building src/d3.cmj
FAILED: src/d3.cmj /Users/javi/Development/sandbox/reason-hello/lib/js/src/d3.js src/d3.cmi 
/Users/javi/.nvm/versions/node/v6.9.4/lib/node_modules/bs-platform/bin/bsc.exe -bs-package-name reason-hello  -bs-package-output commonjs:lib/js/src -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include  -I src   -nostdlib -I '/Users/javi/Development/sandbox/reason-hello/node_modules/bs-platform/lib/ocaml' -bs-super-errors -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -bs-re-error -o src/d3.cmj -c  src/d3.mlast 

  We've found a bug for you!
  
  
  Unbound value <:
  
ninja: build stopped: subcommand failed.
Error: Command failed: /Users/javi/.nvm/versions/node/v6.9.4/lib/node_modules/bs-platform/bin/bsb.exe
Error happened when running command /Users/javi/.nvm/versions/node/v6.9.4/lib/node_modules/bs-platform/bin/bsb.exe with args []
```

**Comment by chenglou** [comment]
(Discussed offline)

This isn't a problem of negative column numbers, which super-errors solves correctly (and I imagine merlin too). Here, the file is literally `""`. I've seen it happen a few times and in this case Reason's parser fails but lost the file name somehow. It's a case we should cover though; might happen with ppx macros.

**Comment by chenglou** [comment]
I've landed https://github.com/BuckleScript/bucklescript/pull/2053 which turns `"_none_"` and `""` into `"(No file name)"` so that they're easier to grep at least.

**Comment by freebroccolo** [comment]
What is the current status of this issue?

**Comment by chenglou** [comment]
This is solved on bsb's super-error side now. Just needs this bsb integration to grep for `(No file name)` I think

**Comment by jchavarri** [comment]
@chenglou your fix upstream was enough to fix bsb, as the lang server parser blindly parses and exposes the error now :v:

![image](https://user-images.githubusercontent.com/220424/32992104-d7ec3892-cd46-11e7-804e-8b5bb81ce23d.png)

Closing!
