### ISSUE TITLE
UnhandledPromiseRejectionWarning when handling compiler diagnostics, fails to write response to client

### ISSUE THREAD

**Issue by j-piecuch** [freebroccolo/ocaml-language-server#36]
I've been trying set up my Neovim for working with OCaml.
Everything is working fine except for compiler diagnostics (I know that the client supports them).
I tried to peek into the messages exchanged between the client and the server using `strace`, and here's what I got:
```
// message from client to server
read(0, "Content-Length: 141\r\n\r\n
  {"params": 
    {"textDocument":
      {"uri":"file:///home/me/projects/ocaml/testproject/src/foo.ml"}
    },
   "method":"textDocument/didSave","jsonrpc":"2.0"
  }",
 65536)

// I'm guessing this is the server talking to Merlin
write(10, 
 "{"context":
    ["auto","file:///home/me/projects/ocaml/testproject/src/foo.ml"],
   "query":
    ["tell","start","end","let () =\n  print_endline 2\n\nlet average a b =\n  (a +. b) /. 2.0\n"]}",
 181)

// Merlin's response
read(12,
 "{"class":"return","value":true,"notifications":[]}\n",
 65536)

// Another query sent to Merlin
write(10,
 "{"context":
    ["auto","file:///home/me/projects/ocaml/testproject/src/foo.ml"],
   "query":["errors"]}",
 97)

// This one has some diagnostic information in it, so it should be forwarded to the client
read(12, 
 "{"class": "return",
   "value":
    [ {"start":
          {"line":2,"col":16},
       "end":
          {"line":2,"col":17},
       "type": "error",
       "sub": [],
       "valid": true,
       "message": "This expression has type int but an expression was expected of type\n         string"
      }
    ],
   "notifications":[]}\n",
 65536)

// Some error (?) occurred
write(2, 
  "(node:9254) UnhandledPromiseRejectionWarning: 
     Unhandled promise rejection (rejection id: 20): 
       Error: <unreachable>: error\n",
 122)

// Nothing gets sent to the client
```

The warning happens only when diagnostics are requested.

**Comment by freebroccolo** [comment]
Hmm, I'm not sure what could be causing that. More information might help.

- Can you provide me with the complete OCaml project you are testing with?
- Can you try vscode with the Reason plugin (which supports OCaml) and see if that fails too?
- How are you configuring Neovim to talk to the server?
- Do you have any problems with other language servers?

**Comment by j-piecuch** [comment]
1. I've uploaded the project for you to see: https://github.com/j-piecuch/issue-ocaml
2. I've installed VS Code, Reason and your plugin, and the same warning appears in the plugin's output every time I make a change to the document. No compiler diagnostics.
3. I don't have any custom configuration as far as the client is concerned, I'm using https://github.com/autozimu/LanguageClient-neovim
4. I'm using language servers for Python and Rust, both work like a charm.

**Comment by freebroccolo** [comment]
Thanks. I will take a look and see if I can reproduce. It sounds like it's probably an issue on the server side if it's happening with both clients/editors. Might be due to some recent API changes upstream but I'm not sure yet.

**Comment by j-piecuch** [comment]
It works fine after a rollback to merlin 2.5.5, I guess an API change in 3.0.0 would explain the issue.

**Comment by j-piecuch** [comment]
I no longer experience the issue with `ocaml-language-server` 1.0.8 and `merlin` 3.0.3, thanks for fixing it!
