### ISSUE TITLE
WSL support

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/ocaml-language-server#45]
See discussion at https://github.com/reasonml-editor/vscode-reasonml/issues/113

There's a PR started for this at https://github.com/freebroccolo/ocaml-language-server/pull/44

Here are some items I would like to see for integrating this into the server (some already there):

- [x] add platform detection functionality
- [x] on windows, check for WSL
- [ ] on windows, check for WSL installed OCaml tooling
- [ ] add setting to "use WSL" (enabled by default): allow user to disable; notify first time
- [ ] implement `ToolingFacade`: modify calls to spawn processes per platform + install kind
- [x] implement `ResourceTransducer`: translate different URIs/paths per platform + install kind

The last few items are mostly about flexibility and are intended to generalize the server so that it can work in situations like having the tools installed through WSL, but not necessarily be WSL specific. This also helps to ensure that we don't allow too much WSL specific logic creep into random parts of the server over time.

**Comment by est31** [comment]
@freebroccolo sorry to disturb you but I'm trying to contact you in the matter of getting the rust-lang/rfcs repo under a proper license. Could you please have a look at this issue: https://github.com/rust-lang/rfcs/issues/2077 ? Thanks!

**Comment by freebroccolo** [comment]
Looks like #53 might be another thing we can fix here.
