### ISSUE TITLE
merlin looks up weird paths after being passed URI to file instead of ordinary path

### ISSUE THREAD

**Issue by j-piecuch** [freebroccolo/ocaml-language-server#53]
I'm using `merlin` 2.5.5, `OCaml` 4.02.3, `ocaml-language-server` 1.0.1.
It started with `merlin` not being able to find symbols defined in other files in the project, 
even though the `.merlin` file was correct and the .cmi files were in the right directories.
I looked at the `ocamlmerlin` process with `strace` to see what paths it was looking up, and the following happens (let's assume that I'm editing a file `/a/b/c/foo.ml`):
- the path passed to `merlin` from the server contains a `file://` prefix, so it's 
`file:///a/b/c/foo.ml`
- `merlin` uses `file:///a/b/c` as input to `chdir`, which obviously fails because of the `file://`
- after that, `merlin` starts looking for the `.merlin` file in weird locations, like
`/a/b/file:/a/b/c/.merlin`, and it doesn't manage to find it

I'm guessing that the problem is caused by the `file://` prefix, but I'm not sure whether `merlin` or `ocaml-language-server` is supposed to handle URIs

**Comment by j-piecuch** [comment]
The issue goes away after I filtered out the `file://` prefixes from the paths sent from the server to `merlin`, so the the way to fix this is either:
- convert URIs to ordinary paths when sending requests to `merlin`, or
- add support for URIs to `merlin`

As I'm stuck with version 2.5.5 of `merlin` because of an earlier unfixed issue, my only hope is the first option

**Comment by freebroccolo** [comment]
Thanks for reporting and investigating this. I'm currently working on some URI rewriting functionality as part of the upcoming WSL support. I suppose I could try to fix this issue simultaneously. I'll look into it.

**Comment by freebroccolo** [comment]
I think this should be fixed now. Let me know if it's still a problem.
