### ISSUE TITLE
`yarn install && yarn run compile` does not build project

### ISSUE THREAD

**Issue by pittsw** [freebroccolo/ocaml-language-server#55]
I tried running `yarn install && yarn run compile` to build the project, but nothing was built.  `yarn install` installed the packages successfully, but when I ran `yarn run compile` it exited after about 2.5 seconds with exit code 0 and declared success, despite not generating any output folders.  I tried running the `tsc` invocation myself, but that did the same thing (exiting after 2.5 seconds with exit code 0).

Node version: v8.6.0
TypeScript version: 2.6.1
OCaml version: 4.05.0
OPAM version: 1.2.2
Merlin version: 3.0.2

If there's an IRC channel, Slack, or Gitter we could chat on I have time between 9am and 5pm, Pacific time to work on this interactively.

**Comment by freebroccolo** [comment]
I'm usually around on the Reason discord server (see the details under "discussion" [here](https://github.com/reasonml-editor/vscode-reasonml#discussion)).

If `yarn run compile` succeeded, you should have a new `./bin` and `./lib` directory in the root. You can run `./bin/server/index.js --stdio` to start the server.

**Comment by pittsw** [comment]
So this is a little embarrassing: I just started using Atom as my editor, and didn't realize that by default it automatically hides folders in your `.gitignore` from the tree view.  Turns out that nothing is wrong, and the files are getting built properly.
