### ISSUE TITLE
FileNotFoundError for 'ocaml-language-server' in sublime text

### ISSUE THREAD

**Issue by jacobbubu** [freebroccolo/ocaml-language-server#64]
I'm using [LSP](https://github.com/tomv564/LSP) in sublime and install `ocaml-language-server` globally with `npm install -g ocaml-language-server`. I've always got the following error in sublime console:

```
reloading settings Packages/User/LSP.sublime-settings
LSP: global clients: eslint=True, ocaml=True, reason=True
Failed to start server
Traceback (most recent call last):
  File "/Users/rongshen/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/main.py", line 253, in start_server
    startupinfo=si)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'ocaml-language-server'
```

**Comment by freebroccolo** [comment]
Thanks for reporting this. From that error message it doesn't appear to be an issue with the language server itself but rather some problem with the Sublime client not being able to find the binary. Can you try opening an issue about this in the repo for the client?

By the way, how do you have your development environment set up? Are you using `nvm` or something like that?

**Comment by jacobbubu** [comment]
Yes, I'm using nvm for my node installation and the global npm binary folder is `/Users/rongshen/.nvm/versions/node/v8.9.1/bin/ocaml-language-server`.

**Comment by freebroccolo** [comment]
I've seen several people have problems using various editor tooling (not just this language server) with `nvm` and similar systems.

I suspect what is happening in your case is that your PATH is not being configured properly to account for the correct nvm path when the plugin tries to start `ocaml-language-server`.

Unfortunately there are any number of reasons why this might be happening. It could be a bug in nvm (there are several issues about stuff like this in the nvm repo), it could be some sort of misconfiguration with your shell init scripts, or something else.

I would recommend trying without nvm and seeing if that helps.

**Comment by jacobbubu** [comment]
Thanks for your suggestion, I'll try to figure it out in LSP or Sublime client.
