### ISSUE TITLE
Renaming will silently fail when program subtly doesn't typecheck

### ISSUE THREAD

**Issue by bsansouci** [freebroccolo/ocaml-language-server#77]
We've have this function:
```reason
let rec recur = (i) => {
  if (i) {
    0
  } else {
    recur(i, 10)
  }
};
let a = recur(1);
```

When trying to rename it to something else, the recursive call does not get renamed. This seems a bit bad because it destroys the trust I'd put in renaming tools. This kind of stuff would cause some very-hard to find bugs.

I'm guessing the reason is that the type checker doesn't know that that call is the same as the one being renamed.

**Comment by freebroccolo** [comment]
The renaming functionality in the server is currently driven by the responses merlin gives to the [occurrences](https://github.com/ocaml/merlin/blob/master/doc/dev/PROTOCOL.md#occurrences--identifier-at-position) query so this is something that would need to be addressed upstream. cc @let-def

Can you open an issue about it in the merlin repo?

**Comment by freebroccolo** [comment]
Closing this since I've created the relevant issue upstream.
