### ISSUE TITLE
Refactor merlin functionality

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/ocaml-language-server#80]
Most of this stuff is in a private branch not yet on `master`.

- [x] provide pre/post-processing hooks for WSL, etc.
- [x] provide a way to deal with response "verbosity" feature
- [x] centralize handling of request failure states
- [x] automatically restart process when appropriate (e.g., edits to `.merlin`)
- [x] support request/response tracing
- [x] make merlin fully optional
- [x] report response notifications
- [x] switch to promise-based handling of cancellations
- [ ] support multi-root (multiple process instances)
- [ ] support batched cancellations for certain classes of requests

**Comment by jordwalke** [comment]
Can you share/describe what you have for `WSL`? I want to make sure that what we're doing is not going to conflict with it.

**Comment by freebroccolo** [comment]
When you say "what we're doing" are you referring to nuclide or something in the reason tooling?

Right now there are two parts to it.

The first is the path translation functionality which is already partly included in `master` (see [here](https://github.com/freebroccolo/ocaml-language-server/blob/master/src/lib/virtual/resource.ts)).

The other part to it is that I have added a mechanism to allow post-processing of merlin requests (after they are constructed but immediately before being sent to `ocamlmerlin`) and pre-processing of merlin responses (immediately after they are received but before they are returned to the calling context).

The intention is that these pre/post-processing hooks will be used to rewrite paths at the `ocaml-language-server` <-> `ocamlmerlin` boundary so that within the different parts of the server logic the calling context for a merlin command is never responsible for additional bookkeeping work.

Does that make sense?

**Comment by jordwalke** [comment]
> When you say "what we're doing" are you referring to nuclide or something in the reason tooling?

I was referring to the `esy-ocaml` support that we're building in `esy`. The diff I landed in `ocaml-language-server` already has the hook in place. What it will enable is making it so no one has to configure the language server to run `bash.exe ocamlmerlin` instead of the defaults. (it does some other stuff too).

Sounds like everything you're planning on will compliment it nicely.

By the way, have you seen the new `wslpath` command? Is it relevant/helpful for your path rewriting work? https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17046

**Comment by freebroccolo** [comment]
> I was referring to the `esy-ocaml` support that we're building in `esy`. The diff I landed in `ocaml-language-server` already has the hook in place. What it will enable is making it so no one has to configure the language server to run `bash.exe ocamlmerlin` instead of the defaults. (it does some other stuff too).

Okay, I see what you mean. Yeah, that should be orthogonal the changes referenced in this thread, but also necessary to get things working nicely for WSL. I did have plans for similar functionality to be incorporated directly into the server but it's not in place yet. In any case, whatever happens there I'll make sure it remains compatible with the `esy` support.

> By the way, have you seen the new `wslpath` command? Is it relevant/helpful for your path rewriting work?

I hadn't seen that but it does appear useful. Looks like I could replace the current ad-hoc rules I've implemented with a call to `wslpath` instead. Thanks for pointing that out.

**Comment by jordwalke** [comment]
> I hadn't seen that but it does appear useful. Looks like I could replace the current ad-hoc rules I've implemented with a call to wslpath instead. Thanks for pointing that out.

It's only available in the most recent release of WSL, so I'm not sure if that's good enough (it will be eventually of course).

**Comment by freebroccolo** [comment]
Yeah, I just noticed that too. It sounds like WSL builds are tied to OS builds so I think it may only currently be available to people using the pre-release update channel. I'll probably have to keep using the ad-hoc implementation for now but eventually I'd like to switch over to `wslpath` once it's widely available.
