### ISSUE TITLE
Compilation error in vscode-reasonml

### ISSUE THREAD

**Issue by jchavarri** [freebroccolo/ocaml-language-server#87]
Not sure exactly why, and this is something that will be caught before publishing, but just in case [this line](https://github.com/reasonml-editor/vscode-reasonml/blob/master/src/client/lifecycle/onWillSaveTextDocument.ts#L15) in `vscode-reasonml` seems to break with some recent change in `/lib/remote` in the lang server.

**Comment by jchavarri** [comment]
The error is in `remote.server.giveFormatted` passed as param to `languageClient.sendRequest`:

```
[ts] Argument of type 'RequestType<TextDocumentItem, string | null, void, void>' is not assignable to parameter of type 'string'.
```

**Comment by jchavarri** [comment]
Using `TextDocumentIdentifier` instead of `TextDocumentItem` in the signature of `giveFormatted` seems to fix it. I'm not very familiar with these types.

**Comment by freebroccolo** [comment]
This is probably due to some recent refactoring in the server for which I haven't pushed the corresponding changes to the extension repo yet. Sorry, I'll get this sorted out a little later today.
