### ISSUE TITLE
Why is reason.formatOnSave needed if there is editor.formatOnSave?

### ISSUE THREAD

**Issue by jchavarri** [freebroccolo/ocaml-language-server#88]
Some users asked in Discord as format on save was not working, and adding `editor.formatOnSave: "true"` seemed to fix the issue.

I've noticed that `refmt` [is called](https://github.com/freebroccolo/ocaml-language-server/blob/master/src/bin/server/feature/documentFormatting.ts#L18) when `documentFormatting` event happens. This event is linked to `editor.formatOnSave` and seems to be independent from `reason.formatOnSave` (works when `editor.formatOnSave` is true, regardless the value in `reason.formatOnSave`).

Why calling refmt again through the `register` function [in `onWillSaveTextDocument`](https://github.com/reasonml-editor/vscode-reasonml/blob/master/src/client/lifecycle/onWillSaveTextDocument.ts#L27-L33) in `vscode-reasonml`, with a [different code path](https://github.com/freebroccolo/ocaml-language-server/blob/bb329ae64bee2aba29faf4885910960e0a8d1111/src/bin/server/request/giveFormatted.ts#L8)? (side note: i'm not sure this code path works, i've tried to print something after [this line](https://github.com/reasonml-editor/vscode-reasonml/blob/master/src/client/lifecycle/onWillSaveTextDocument.ts#L15) in the client, but i believe the server crashes and that `await` never resolves).

**Comment by freebroccolo** [comment]
I think this is a bug -- something that got missed during a refactoring. The extension shouldn't need to be using a custom request in the save hook anymore. I'll check it out but I think we can probably remove `onWillSaveTextDocument` entirely at this point.

**Comment by jchavarri** [comment]
> I think we can probably remove `onWillSaveTextDocument` entirely at this point. 

I went ahead and did that as I had been looking at that code and it was fresh enough :) please let me know if there's anything that should change, thanks!
