### ISSUE TITLE
The server cannot initialize when "initializationOptions" is set to null

### ISSUE THREAD

**Issue by stevenremot** [freebroccolo/ocaml-language-server#96]
I recently installed the [lsp-ocaml](https://github.com/emacs-lsp/lsp-ocaml) emacs package and ocaml-language-server, and I got this error when running `lsp-ocaml-enable` to start the client:

```
Error from the Language Server: Request initialize failed with message: Cannot read property ’path’ of null (Internal Error)
```

I investigated a bit, it looks like when lsp-ocaml sends the "initialize" request, the field `initializationOptions` is set to `null`, which sets `settings.reason` to null in the server.

I wasn't really sure if I should create this issue here or on lsp-ocaml repository directly... Should the language server fill proper defaults in this case, or should the client send something else than `null` ?

**Comment by zploskey** [comment]
I think I am getting the same error using LanguageClient-neovim. When I open a reason file it displays
```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "error": {
    "code": -32603,
    "message": "Request initialize failed with message: Cannot read property 'path' of null"
  }
}
```
on a line at the bottom of the window.

**Comment by freebroccolo** [comment]
Thanks for the report. I'm assuming you are testing with `1.0.26`. Can one of you check if this also happens with version `1.0.23`?

**Comment by freebroccolo** [comment]
I suspect this may be due to changes from #95. cc @pittsw

**Comment by zploskey** [comment]
I do no not see the error on 1.0.23. I see an error on 1.0.26.

**Comment by freebroccolo** [comment]
Can one of you try with the `1.0.27` version I just published?

**Comment by stevenremot** [comment]
I confirm it solved the problem for me too, thanks!
